server:
  port: 8001

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: zsr1401407..
    url: jdbc:mysql://localhost:3306/product?useSSL=false&serverTimezone=GMT%2B8

  application:
    name: testdemo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8671/eureka